---
title: "Survival BrCa"
author: "Alex Paynter"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F,
                      message = F, warning = F)
```

```{r}
library(cli) # prevents an error on version reliance.
library(readr)
library(vctrs)
library(rlang)
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(magrittr)
library(janitor)
library(glue)
library(ggplot2)
library(huxtable)

library(survival)
library(survminer)

purrr::walk(
  .x = here("R", dir(here("R"))), 
  .f = source
)
```


```{r, read_data_filter_cohort}
read_wrap <- function(f) {
  readr::read_csv(
    file = here("data-raw", f),
    show_col_types = F
  )
}

dft_pt <- read_wrap("patient_level_dataset.csv")
dft_ca_ind <- read_wrap("cancer_level_dataset_index.csv")
dft_cpt <- read_wrap("cancer_panel_test_level_dataset.csv")

vec_not_sarcoma <- dft_ca_ind %>%
  filter(!(ca_hist_adeno_squamous %in% "Sarcoma")) %>%
  pull(record_id)

# Filter down to non-sarcoma patients, and take the first index cancer
#   for participants who have more than one.
dft_pt %<>% filter_df_by_rid(., rid_vec = vec_not_sarcoma)
dft_ca_ind %<>% filter_df_by_rid(., rid_vec = vec_not_sarcoma) %>%
  group_by(record_id) %>%
  slice(1) %>%
  ungroup(.)
# Only CPTs associated with the index cancer:
dft_cpt %<>%
  inner_join(
    .,
    select(dft_ca_ind, record_id, ca_seq),
    by = c("record_id", "ca_seq")
  ) 

```


```{r}
dft_first_cpt <- dft_cpt %>%
  group_by(record_id) %>%
  arrange(dx_cpt_rep_yrs) %>%
  slice(1) %>%
  ungroup(.) %>%
  select(record_id, ca_seq, cpt_number,
         dx_cpt_rep_yrs, cpt_report_post_death)
  
dft_surv <- left_join(
  dft_ca_ind,
  dft_first_cpt,
  by = c("record_id", "ca_seq")
)

# Practical limitation:
dft_surv %<>%
  filter(dx_cpt_rep_yrs < tt_os_dx_yrs)

surv_obj_os <- with(
  dft_surv,
  Surv(
    time = dx_cpt_rep_yrs,
    time2 = tt_os_dx_yrs,
    event = os_dx_status)
)

summary(surv_obj_os)

```

