---
title: "Survival from metastasis"
output: beamer_presentation
date: "2023-09-07"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = F,
                      fig.width = 7, fig.height = 5,
                      warning = F, message = F)
```



```{r}
library(fs)
library(purrr)
library(here)
purrr::walk(.x = fs::dir_ls(here("R")), .f = source)
```




```{r}
read_wrap_surv_sums <- function(file) {
  readr::read_rds(
    here('data', 'survival', 'fit_outputs', 'fit_summary',
         paste0(file, '.rds')
    )
  ) 
}




write_wrap_surv_sum(
  dft_coef_dmet_os_all,
     "coef_dmet_os_all"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_trip_neg,
     "coef_dmet_os_trip_neg"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_hr_pos_her2_neg,
  "coef_dmet_os_hr_pos_her2_neg"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_her2_pos,
  "coef_dmet_os_her2_pos"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_all_no_conf,
  "coef_dmet_os_all_no_conf"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_trip_neg_no_conf,
  "coef_dmet_os_trip_neg_no_conf"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_hr_pos_her2_neg_no_conf,
  "coef_dmet_os_hr_pos_her2_neg_no_conf"
)
write_wrap_surv_sum(
  dft_coef_dmet_os_her2_pos_no_conf,
  "coef_dmet_os_her2_pos_no_conf"
)








# Can replace these once you go back and fix the survival function creator:
dft_dmet_surv_all <- readr::read_rds(
  file = here('data', 'survival', 'prepared_data',
              'surv_dmet_all.rds')
)
dft_dmet_surv_trip_neg <- readr::read_rds(
  file = here('data', 'survival', 'prepared_data',
              'surv_dmet_trip_neg.rds')
)
dft_dmet_surv_hr_pos_her2_neg <- readr::read_rds(
  file = here('data', 'survival', 'prepared_data',
              'surv_dmet_hr_pos_her2_neg.rds')
)
dft_dmet_surv_her2_pos <- readr::read_rds(
  file = here('data', 'survival', 'prepared_data',
              'surv_dmet_her2_pos.rds')
)

```



# Results


```{r}



gg_rel_scatter_os_all <- plot_hr_rel_scatter(
  dft_coef_dmet_os_all,
  plot_title = "OS prognostic variables from distant metastasis",
  plot_subtitle = "Reliability is the frequency of identification in a boostrapped regularized LTRC Cox model"
)

gg_rel_scatter_os_trip_neg <- plot_hr_rel_scatter(
  dft_coef_dmet_os_trip_neg,
  plot_title = "OS prognostic variables from distant metastasis (triple negative subgroup)",
  plot_subtitle = "Reliability is the frequency of identification in a boostrapped regularized LTRC Cox model"
)

gg_rel_scatter_os_hr_pos_her2_neg <- plot_hr_rel_scatter(
  dft_coef_dmet_os_hr_pos_her2_neg,
  plot_title = "OS prognostic variables from distant metastasis (HR+/HER2- subgroup)",
  plot_subtitle = "Reliability is the frequency of identification in a boostrapped regularized LTRC Cox model"
)
  
gg_rel_scatter_os_her2_pos <- plot_hr_rel_scatter(
  dft_coef_dmet_os_her2_pos,
    plot_title = "OS prognostic variables from distant metastasis (HER2+ subgroup)",
  plot_subtitle = "Reliability is the frequency of identification in a boostrapped regularized LTRC Cox model"
)
```


---

```{r, include = T}
gg_rel_scatter_os_all
```


```{r}
binary_helper <- function(vec, zero = "Wild Type", one = "Altered") {
  case_when(
    vec %in% 0 ~ zero,
    vec %in% 1 ~ one,
    T ~ "error"
  ) %>%
    factor(., levels = c(zero, one))
}

gg_surv_dmet_all_tp53_mut <- dft_dmet_surv_all %>%
  mutate(TP53_mut = binary_helper(TP53_mut)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "TP53_mut"
  )

gg_surv_dmet_all_ERBB2_cna <- dft_dmet_surv_all %>%
  mutate(ERBB2_cna = binary_helper(ERBB2_cna)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "ERBB2_cna"
  )

gg_surv_dmet_all_stage_iv <- dft_dmet_surv_all %>%
  mutate(stage_dx_iv_num = binary_helper(
    stage_dx_iv_num,
    zero = "Stage I-III at dx",
    one = "Stage IV at dx")
  ) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "stage_dx_iv_num"
  )
```



---

```{r, include = T}
gg_surv_dmet_all_tp53_mut
```

---

```{r, include = T}
gg_surv_dmet_all_ERBB2_cna
```

---

```{r, include = T}
gg_surv_dmet_all_stage_iv
```




---

```{r, include = T}
gg_rel_scatter_os_hr_pos_her2_neg
```

```{r, include = T}
gg_surv_dmet_hr_pos_her2_neg_1 <- dft_dmet_surv_hr_pos_her2_neg %>%
  mutate(TP53_mut = binary_helper(TP53_mut)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "TP53_mut"
  )

gg_surv_dmet_hr_pos_her2_neg_2 <- dft_dmet_surv_hr_pos_her2_neg %>%
  mutate(DNMT3A_mut = binary_helper(DNMT3A_mut)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "DNMT3A_mut"
  )

gg_surv_dmet_hr_pos_her2_neg_3 <- dft_dmet_surv_hr_pos_her2_neg %>%
  mutate(MYC_cna = binary_helper(MYC_cna)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "MYC_cna"
  )

```



---

```{r, include = T}
gg_surv_dmet_hr_pos_her2_neg_1
```

---

```{r, include = T}
gg_surv_dmet_hr_pos_her2_neg_2
```

---

```{r, include = T}
gg_surv_dmet_hr_pos_her2_neg_3
```

---

```{r, include = T}
gg_rel_scatter_os_her2_pos
```


```{r, include = T}
gg_surv_dmet_her2_pos_1 <- dft_dmet_surv_her2_pos %>%
  mutate(ERBB2_cna = binary_helper(ERBB2_cna)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "ERBB2_cna"
  )

```

---

```{r, include = T}
gg_surv_dmet_her2_pos_1
```



---

```{r, include = T}
gg_rel_scatter_os_trip_neg
```

```{r, include = T}
gg_surv_dmet_trip_neg <- dft_dmet_surv_trip_neg %>%
  mutate(MYCL_cna = binary_helper(MYCL_cna)) %>%
  plot_km_dmet_binary_strata(
    dat = .,
    strata = "MYCL_cna"
  )

```






```{r}
dft_coef_combined <- bind_rows(
  mutate(dft_coef_dmet_os_all, strata = "All"),
  mutate(dft_coef_dmet_os_trip_neg, strata = "Triple Negative"),
  mutate(dft_coef_dmet_os_hr_pos_her2_neg, strata = "HR+/HER2-"),
  mutate(dft_coef_dmet_os_her2_pos, strata = "HER2+")
) %>%
  filter(stability > 0.3) %>%
  mutate(strata = forcats::fct_inorder(strata))
```

---

```{r, include = T}
plot_hr_forest_multi(dft_coef_combined, strat_var = "strata") + 
  labs(title = "Features with over 30% stability over all models")
```